export const actionTypes = {
    GET_ALL_GENERATIONS_START: "GET_ALL_GENERATIONS_START",
    GET_ALL_GENERATIONS_SUCCESS: "GET_ALL_GENERATIONS_SUCCESS",
    GET_ALL_GENERATIONS_FINISH: "GET_ALL_GENERATIONS_FINISH",
}